docs_desc: str = """
        Mini social network backend service for posts, comments, and likes.\n\n"
        "## Authentication\n"
        "JWT-based authentication with short-lived access tokens and long-lived refresh tokens. "
        "Passwords are hashed with **bcrypt**.\n\n"
        "## User Management\n"
        "User profile management including registration, verification, and profile updates.\n\n"
        "## Social Features\n"
        "Posts, comments, and likes with role-based access control. Create, edit, and delete your posts. "
        "Comment on others' posts. Like posts (no self-likes, one per user).\n\n"
        "## Verification\n"
        "Email verification flow with 6-digit codes. Unverified accounts are automatically "
        "purged after 24 hours via a Celery Beat scheduled task.\n\n"
        "## Infrastructure\n"
        "PostgreSQL · Redis · Celery · Docker Compose
        """
